apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: microkafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: docker.io/bitnami/kafka:3.6.1-debian-11-r0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ENABLE_KRAFT
              value: "yes"

            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "7Dvn0OLMQo-bg4qmCmflVg"

            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(POD_NAME).kafka.microkafka.svc.cluster.local:9092"

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"

            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"

            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: KAFKA_CFG_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['controller.kubernetes.io/pod-index']

            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: |
                0@kafka-0.kafka.microkafka.svc.cluster.local:9093,
                1@kafka-1.kafka.microkafka.svc.cluster.local:9093,
                2@kafka-2.kafka.microkafka.svc.cluster.local:9093
