apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: microkafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: localhost:32000/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            # REQUIRED for KRaft
            - name: CLUSTER_ID
              value: "7Dvn0OLMQo-bg4qmCmflVg"

            # Correct numeric broker.id
            - name: KAFKA_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['controller.kubernetes.io/pod-index']

            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOSTNAME).kafka.microkafka.svc.cluster.local:9092"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"

            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: |
                0@kafka-0.kafka.microkafka.svc.cluster.local:9093,
                1@kafka-1.kafka.microkafka.svc.cluster.local:9093,
                2@kafka-2.kafka.microkafka.svc.cluster.local:9093
