apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: microkafka
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: quay.io/strimzi/kafka:0.39.0-kafka-3.6.1
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              set -e
              export NODE_ID=${HOSTNAME##*-}

              echo "Formatting Kafka storage (node.id=${NODE_ID})"
              bin/kafka-storage.sh format \
                -t 7Dvn0OLMQo-bg4qmCmflVg \
                -c config/kraft/server.properties \
                --ignore-formatted

              echo "Starting Kafka broker ${NODE_ID}"
              exec bin/kafka-server-start.sh config/kraft/server.properties
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "$(NODE_ID)"

            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"

            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"

            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOSTNAME).kafka.microkafka.svc.cluster.local:9092"

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"

            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"

            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: |
                0@kafka-0.kafka.microkafka.svc.cluster.local:9093,
                1@kafka-1.kafka.microkafka.svc.cluster.local:9093,
                2@kafka-2.kafka.microkafka.svc.cluster.local:9093
