apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-admin
  namespace: microkafka
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-admin
          image: ashwinsai22/kafka-admin:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka.microkafka.svc.cluster.local:9092
