apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-admin
  namespace: microkafka
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure

      initContainers:
        - name: wait-for-kafka
          image: confluentinc/cp-kafka:7.6.0
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for Kafka broker..."
              until kafka-broker-api-versions \
                --bootstrap-server kafka-0.kafka.microkafka.svc.cluster.local:9092 >/dev/null 2>&1
              do
                sleep 3
              done

              echo "⏳ Waiting for group coordinator..."
              until kafka-consumer-groups \
                --bootstrap-server kafka-0.kafka.microkafka.svc.cluster.local:9092 \
                --list >/dev/null 2>&1
              do
                sleep 3
              done

              echo "✅ Kafka fully ready"

      containers:
        - name: kafka-admin
          image: ashwinsai22/kafka-admin:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka.microkafka.svc.cluster.local:9092