apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-admin
  namespace: microkafka
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: kafka-admin
          image: confluentinc/cp-kafka:7.6.0
          imagePullPolicy: IfNotPresent
          command:
            - bash
            - -ec
            - |
              echo "Waiting for Kafka..."
              sleep 20
              node admin.js
          env:
            - name: KAFKA_BROKERS
              value: >
                kafka-0.kafka.microkafka.svc.cluster.local:9092