apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microkafka-api-ingress
  namespace: microkafka
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public
  tls:
    - hosts:
        - microkafka-api.bezawada.link
      secretName: microkafka-api-tls
  rules:
    - host: microkafka-api.bezawada.link
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 80

          - path: /payment-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: payment-service
                port:
                  number: 80

          - path: /order-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 80

          - path: /email-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: email-service
                port:
                  number: 80

          - path: /analytic-service(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: analytic-service
                port:
                  number: 80

          - path: /kafka-ui(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kafka-ui
                port:
                  number: 80
