apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - kafka/kafka-headless.yaml
  - kafka/kafka-statefulset.yaml
  - kafka/kafka-ui.yaml
  - kafka/kafka-ui-svc.yaml
  - services/order.yaml
  - services/payment.yaml
  - services/email.yaml
  - services/analytic.yaml
  - services/client.yaml
