apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic-service
  namespace: microkafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic-service
  template:
    metadata:
      labels:
        app: analytic-service
    spec:
      containers:
        - name: analytic
          image: ashwinsai22/analytic-service:latest
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKER
              value: kafka-kafka-bootstrap:9092
---
apiVersion: v1
kind: Service
metadata:
  name: analytic-service
  namespace: microkafka
spec:
  selector:
    app: analytic-service
  ports:
    - port: 80
      targetPort: 3000
