apiVersion: v1
kind: Service
metadata:
  name: analytic-service
  namespace: microkafka
spec:
  type: ClusterIP
  selector:
    app: analytic-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
