apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytic-service
  namespace: microkafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytic-service
  template:
    metadata:
      labels:
        app: analytic-service
    spec:
      containers:
        - name: analytic
          image: localhost:32000/analytic-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka.microkafka.svc.cluster.local:9092,kafka-1.kafka.microkafka.svc.cluster.local:9092,kafka-2.kafka.microkafka.svc.cluster.local:9092
---
apiVersion: v1
kind: Service
metadata:
  name: analytic-service
  namespace: microkafka
spec:
  selector:
    app: analytic-service
  ports:
    - port: 80
      targetPort: 3000
