apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - payment-deployment.yaml
  - payment-service.yaml
  - order-deployment.yaml
  - order-service.yaml
  - email-deployment.yaml
  - email-service.yaml
  - analytic-deployment.yaml
  - analytic-service.yaml
