apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: microkafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      initContainers:
        - name: wait-for-kafka
          image: busybox:1.36
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for Kafka..."
              until nc -z kafka-0.kafka.microkafka.svc.cluster.local 9092; do
                sleep 2
              done
              echo "✅ Kafka is ready"

      containers:
        - name: order-service
          image: ashwinsai22/order-service:latest
          imagePullPolicy: Always
          env:
            - name: KAFKA_BROKERS
              value: kafka-0.kafka.microkafka.svc.cluster.local:9092
          ports:
            - containerPort: 8000
